use_frameworks!

platform :ios, '8.0'

target 'HMADFramework_Example' do
  pod 'HMADFramework', :path => '../'

  target 'HMADFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
